### ISSUE TITLE
Issue: Plugin crashed

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#200]
Hi,

I have a lot of difficulties with version 0.0.51:
- **Slowness**: even by setting the `-parallelism` parameter to a value of `1`, resources take a loooong time to create and sometimes they are created in Jamf Pro but Terraform continues to try to create them.
- **`terraform apply` updates resources that didn't change**:  in `jamfpro_computer_extension_attribute` for example when I fill the `script` attribute with the content a local file.
- **Crash**: see the last crash log below. It occurs when I performed a `terraform plan`, without any changes.

```
Stack trace from the terraform-provider-jamfpro_v0.0.51 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104ea69ec]

goroutine 113 [running]:
github.com/deploymenttheory/go-api-http-client/authenticationhandler.(*AuthTokenHandler).BasicAuthTokenAcquisition(0x1400033a840, {0x105a2c3f8, 0x1400029c5a0}, 0x1400029c660, {0x14000541408, 0x8}, {0x140005413e0, 0xd})
	github.com/deploymenttheory/go-api-http-client@v0.1.37/authenticationhandler/basicauthentication.go:37 +0x36c
github.com/deploymenttheory/go-api-http-client/authenticationhandler.(*AuthTokenHandler).obtainNewToken(0x1400033a840, {0x105a2c3f8?, 0x1400029c5a0?}, 0x0?, {{0x14000541408, 0x8}, {0x140005413e0, 0xd}, {0x0, 0x0}, ...})
	github.com/deploymenttheory/go-api-http-client@v0.1.37/authenticationhandler/tokenmanager.go:47 +0x98
github.com/deploymenttheory/go-api-http-client/authenticationhandler.(*AuthTokenHandler).CheckAndRefreshAuthToken(0x1400033a840, {0x105a2c3f8, 0x1400029c5a0}, 0x1400029c660, {{0x14000541408, 0x8}, {0x140005413e0, 0xd}, {0x0, 0x0}, ...}, ...)
	github.com/deploymenttheory/go-api-http-client@v0.1.37/authenticationhandler/tokenmanager.go:18 +0xc0
github.com/deploymenttheory/go-api-http-client/httpclient.(*Client).executeRequestWithRetries(0x14000154b60, {0x10555cf1f, 0x3}, {0x14000040918, 0x18}, {0x0, 0x0}, {0x1057bff00, 0x140005b64f8})
	github.com/deploymenttheory/go-api-http-client@v0.1.37/httpclient/request.go:127 +0x260
github.com/deploymenttheory/go-api-http-client/httpclient.(*Client).DoRequest(0x14000154b60, {0x10555cf1f, 0x3}, {0x14000040918, 0x18}, {0x0, 0x0}, {0x1057bff00, 0x140005b64f8})
	github.com/deploymenttheory/go-api-http-client@v0.1.37/httpclient/request.go:72 +0x380
github.com/deploymenttheory/go-api-sdk-jamfpro/sdk/jamfpro.(*Client).GetSiteByID(0x14000447380, 0x46)
	github.com/deploymenttheory/go-api-sdk-jamfpro@v1.5.12/sdk/jamfpro/classicapi_sites.go:55 +0xe0
github.com/deploymenttheory/terraform-provider-jamfpro/internal/endpoints/sites.ResourceJamfProSitesRead({0x105a23b90?, 0x140005ab920?}, 0x140005f0780, {0x1057c76c0?, 0x140004de730?})
	github.com/deploymenttheory/terraform-provider-jamfpro/internal/endpoints/sites/sites_resource.go:139 +0x1dc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x140004bb880, {0x105a23b90, 0x140005ab920}, 0x140005f0780, {0x1057c76c0, 0x140004de730})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:795 +0xe4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140004bb880, {0x105a23b90, 0x140005ab920}, 0x140005fa8f0, {0x1057c76c0, 0x140004de730})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x408
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140003d8708, {0x105a23b90?, 0x140005ab860?}, 0x140005a6440)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x3e4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140004d2000, {0x105a23b90?, 0x140005aa150?}, 0x14000096480)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:775 +0x3c8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1059d0120, 0x140004d2000}, {0x105a23b90, 0x140005aa150}, 0x140005f0000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001c1200, {0x105a23b90, 0x140005aa030}, {0x105a29c00, 0x140004f6000}, 0x140009a19e0, 0x14000495800, 0x106297fc8, 0x0)
	google.golang.org/grpc@v1.61.1/server.go:1385 +0xb40
google.golang.org/grpc.(*Server).handleStream(0x140001c1200, {0x105a29c00, 0x140004f6000}, 0x140009a19e0)
	google.golang.org/grpc@v1.61.1/server.go:1796 +0xc00
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.61.1/server.go:1029 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
	google.golang.org/grpc@v1.61.1/server.go:1040 +0x13c

Error: The terraform-provider-jamfpro_v0.0.51 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Don't hesitate if you need complementary informations, I will continue to test with pleasure!
But please note I will ooo until May the 13rd.

Regards,
Emmanuel

**Comment by ShocOne** [comment]
Hi Emmanuel, the logs suggest an issue in the http client. i've added a bug fix to how the resp is handled when Basic Auth Token Acquisition fails. this should resolve the nil pointer dereference. 

for your other issue with the `jamfpro_computer_extension_attribute`, please check if you have any trailing whitespace for your script payload and ensure to remove it. jamf pro removes trailing whitespace on it's server side. which might be related

**Comment by ecanault** [comment]
You're right for the `jamfpro_computer_extension_attribute`: it's not an issue but the *new line* character at the end of the script.

Thanks a lot!
You can close this one 🙂
